name: Tests

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test-edge-cases:
    runs-on: ubuntu-latest
    name: Edge Cases
    steps:
      - uses: actions/checkout@v5

      - name: Use Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "22"
          cache: "yarn"

      - name: 📦 Install dependencies
        run: yarn install --immutable

      - name: Run tests
        run: yarn test --verbose
